# Generated by Django 3.1.7 on 2021-04-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=10)),
                ('manufacturer', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Passenger',
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('departure_time', models.DateTimeField(verbose_name='Departure Time')),
                ('duration', models.TimeField(verbose_name='Duration')),
                ('aircraft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aircraft')),
                ('attendance', models.ManyToManyField(blank=True, to='core.Passenger')),
            ],
        ),
    ]
