# Generated by Django 3.1.7 on 2021-04-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210406_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='attendance',
            field=models.ManyToManyField(blank=True, to='core.Passenger'),
        ),
    ]
